DISTRO_FEATURES:remove += "alsa bluetooth ext2 pcmcia 3g nfc x11 bluez5"

# Value to define
LCM_SYSBUS ??= "ubus"
# QA check settings - a little stricter than the OE-Core defaults
WARN_TO_ERROR_QA = "already-stripped compile-host-path install-host-path \
                    installed-vs-shipped ldflags pn-overrides rpaths staticdev \
                    unknown-configure-option useless-rpaths"
WARN_QA:remove = "${WARN_TO_ERROR_QA}"
ERROR_QA:append = " ${WARN_TO_ERROR_QA}"

PREFERRED_VERSION_openssl ?= "1.1.1o"
PREFERRED_VERSION_nativesdk-openssl ?= "1.1.1o"
HOSTTOOLS_NONFATAL += "git-lfs"
PACKAGE_CLASSES ?= "package_ipk"

VIRTUAL-RUNTIME_init_manager ?= "sysvinit"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "systemd"
MACHINE_FEATURES_BACKFILL_CONSIDERED += "rtc qemu-usermode"

# We don't need sysVinit VT's
USE_VT = "0"

# Enable security flags on compiler/linker
require conf/distro/include/security_flags.inc
## Disable stringformat security
SECURITY_STRINGFORMAT = ""