#OCI configuration


OCI_IMAGE_AUTHOR ??= "${PATCH_GIT_USER_NAME}"
OCI_IMAGE_AUTHOR_EMAIL ??= "${PATCH_GIT_USER_EMAIL}"

OCI_IMAGE_TAG ??= "latest"
OCI_IMAGE_RUNTIME_UID ??= ""

OCI_IMAGE_ARCH ??= "${TARGET_ARCH}"
OCI_IMAGE_SUBARCH ??= "${@oci_map_subarch(d.getVar('TARGET_ARCH'), d.getVar('TUNE_FEATURES'), d)}"

OCI_IMAGE_ENTRYPOINT ??= "/sbin/init"
OCI_IMAGE_ENTRYPOINT_ARGS ??= "/bin/sh"
OCI_IMAGE_WORKINGDIR ??= "/"

# List of ports to expose from a container running this image:
#  PORT[/PROT]  
#     format: <port>/tcp, <port>/udp, or <port> (same as <port>/tcp).
OCI_IMAGE_PORTS ??= ""

# key=value list of labels
OCI_IMAGE_LABELS ??= ""
# key=value list of environment variables
OCI_IMAGE_ENV_VARS ??= ""

# whether the oci image dir should be left as a directory, or
# bundled into a tarball.
OCI_IMAGE_TAR_OUTPUT ??= "true"
