#@TYPE: Machine
#@NAME: RaspberryPi 3 Development Board (32bit)
#@DESCRIPTION: Machine configuration for the RaspberryPi 3 container in 32 bits mode

DEFAULTTUNE ?= "cortexa7thf-neon-vfpv4"
require conf/machine/include/arm/armv7a/tune-cortexa7.inc
require conf/machine/include/machine-container-common.inc

#For runqemu
QB_SYSTEM_NAME = "qemu-system-arm"

