#@TYPE: Machine
#@NAME: qemumips32r2
#@DESCRIPTION: Machine configuration for the MIPS 32r2 + Big Endian + Hard Float container

DEFAULTTUNE ?= "mips32r2"

require conf/machine/include/mips/tune-mips32r2.inc
require conf/machine/include/machine-container-common.inc


#For runqemu
QB_SYSTEM_NAME = "qemu-system-mips"
