#@TYPE: Machine
#@NAME: RaspberryPi 3 Development Board (32bit)
#@DESCRIPTION: Machine configuration for the RaspberryPi 3 container in 64 bits mode

require conf/machine/include/arm/armv8a/tune-cortexa53.inc
require conf/machine/include/machine-container-common.inc

#For runqemu
QB_SYSTEM_NAME = "qemu-system-aarch64"

