# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-lcm-containers"
BBFILE_PATTERN_meta-lcm-containers = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-lcm-containers = "9"

LAYERDEPENDS_meta-lcm-containers = "core"
LAYERDEPENDS_meta-lcm-containers += "virtualization-layer"
LAYERDEPENDS_meta-lcm-containers += "meta-usp"
LAYERDEPENDS_meta-lcm-containers += "meta-amx"
LAYERSERIES_COMPAT_meta-lcm-containers = "honister"

# By default built debugfs
IMAGE_GEN_DEBUGFS ?= "1"
IMAGE_FSTYPES_DEBUGFS ?= "tar.bz2"
PACKAGE_DEBUG_SPLIT_STYLE ?= "debug-without-src"
