# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-containers"
BBFILE_PATTERN_meta-containers = "^${LAYERDIR}/"

LAYERDEPENDS_meta-containers = "core"
LAYERDEPENDS_meta-containers = "yoctobsp"
LAYERDEPENDS_meta-containers += "virtualization-layer"
LAYERDEPENDS_meta-containers += "meta-usp"
LAYERDEPENDS_meta-containers += "meta-amx"

LAYERSERIES_COMPAT_meta-containers = "honister"
