# needed for pcb-sysbus serializers
CONFIG_PCB_HELP_SUPPORT = "y"

# Include the /lib/libpcb_%.so symlink in the normal package
FILES:${PN}-dev = ""
FILES:${PN} = ""
FILES:${PN}-staticdev = ""

FILES:${PN} += "/usr/share/sah_config/libpcb.cfg"
FILES:${PN}-dev = "/usr/lib/pkgconfig/*.pc"

FILES:${PN}-dev += "${INCLUDEDIR}/pcb/common/*.h"
FILES:${PN}-dev += "${INCLUDEDIR}/pcb/common/*.h"
FILES:${PN}-dev += "${INCLUDEDIR}/pcb/utils/*.h"
FILES:${PN}-dev += "${INCLUDEDIR}/pcb/common.h"
FILES:${PN}-dev += "${INCLUDEDIR}/pcb/utils.h"
FILES:${PN}-dev += "${INCLUDEDIR}/pcb/core/*.h"
FILES:${PN}-dev += "${INCLUDEDIR}/pcb/core.h"
FILES:${PN}-dev += "${INCLUDEDIR}/pcb/pcb_client.h"
FILES:${PN} += "/lib/libpcb_utils${SOLIBS}"
FILES:${PN} += "/lib/libpcb_preload${SOLIBS}"
FILES:${PN} += "/lib/libpcb_sl${SOLIBS}"
FILES:${PN}-staticdev += "/lib/libpcb_utils.a"
FILES:${PN}-staticdev += "/lib/libpcb_sl.a"
FILES:${PN} += "/lib/libpcb_ssl${SOLIBS}"
FILES:${PN} += "/lib/libpcb_utils_sendfile${SOLIBS}"
FILES:${PN}-dev += "/lib/libpcb_utils_sendfile${SOLIBSDEV}"
FILES:${PN}-staticdev += "/lib/libpcb_ssl_pic.a"
FILES:${PN}-dev += "${PKG_CONFIG_LIBDIR}/pcb_utils.pc"
FILES:${PN}-dev += "${PKG_CONFIG_LIBDIR}/pcb_sockets.pc"
FILES:${PN}-dev += "${PKG_CONFIG_LIBDIR}/pcb_secure_sockets.pc"
FILES:${PN} += "/lib/libpcb_dm${SOLIBS}"
FILES:${PN}-staticdev += "/lib/libpcb_dm.a"
FILES:${PN}-dev += "${PKG_CONFIG_LIBDIR}/pcb.pc"
FILES:${PN}-dev += "${PKG_CONFIG_LIBDIR}/pcbssl.pc"
FILES:${PN}-dev += "${PKG_CONFIG_LIBDIR}/pcbsendfile.pc"

FILES:${PN} += "/lib/libpcb_dm${SOLIBSDEV}"
FILES:${PN} += "/lib/libpcb_utils${SOLIBSDEV}"
FILES:${PN} += "/lib/libpcb_utils_sendfile${SOLIBSDEV}"
FILES:${PN} += "/lib/libpcb_ssl${SOLIBSDEV}"
FILES:${PN} += "/lib/libpcb_sl${SOLIBSDEV}"
FILES:${PN} += "/lib/libpcb_preload${SOLIBSDEV}"

FILES_SOLIBSDEV = ""
INSANE_SKIP:${PN} += "dev-so"
