require conf/distro/include/lcm-containers-distro.inc

DISTRO = "meta-containers"
DISTRO_NAME = "LCM Containers Base Distro for systemd"
DISTRO_VERSION = "0.0.5"

DISTRO_FEATURES:append = " virtualization"

INIT_MANAGER = "systemd"

PACKAGECONFIG:remove:pn-systemd = "resolved"
PACKAGECONFIG:remove:pn-systemd = "nss-resolve"
PACKAGECONFIG:remove:pn-systemd = "userdb"
