# This component attempts to generate a bitbake recipe from Rust cargo formatted compoonent. 
inherit cargo

CARGO_SRC_DIR = ""

DEPENDS += "openssl"

LICENSE = "MIT & Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE-MIT;md5=7cf7448427a9aa9aafc10412b7da2225 \
                    file://LICENSE-APACHE;md5=1836efb2eb779966696f473ee8540542 "

SRC_URI = "git://github.com/meta-rust/cargo-bitbake;protocol=https;branch=master"

# Modify these as desired
PV = "1.0+git${SRCPV}"
SRCREV = "77c1f66e61d8a006a1ddb01f023084e4e183644b"

S = "${WORKDIR}/git"


SRC_URI += "crate://crates.io/anyhow/1.0.57"
SRC_URI += "crate://crates.io/cargo/0.61.1"
SRC_URI += "crate://crates.io/git2/0.14.3"
SRC_URI += "crate://crates.io/itertools/0.10.3"
SRC_URI += "crate://crates.io/lazy_static/1.4.0"
SRC_URI += "crate://crates.io/md5/0.7.0"
SRC_URI += "crate://crates.io/regex/1.5.5"
SRC_URI += "crate://crates.io/structopt/0.3.26"
SRC_URI += "crate://crates.io/atty/0.2.14"
SRC_URI += "crate://crates.io/bytesize/1.1.0"
SRC_URI += "crate://crates.io/cargo-platform/0.1.2"
SRC_URI += "crate://crates.io/cargo-util/0.1.2"
SRC_URI += "crate://crates.io/clap/3.1.16"
SRC_URI += "crate://crates.io/clap/2.34.0"
SRC_URI += "crate://crates.io/crates-io/0.34.0"
SRC_URI += "crate://crates.io/crossbeam-utils/0.8.8"
SRC_URI += "crate://crates.io/curl/0.4.43"
SRC_URI += "crate://crates.io/curl-sys/0.4.54+curl-7.83.0"
SRC_URI += "crate://crates.io/env_logger/0.9.0"
SRC_URI += "crate://crates.io/filetime/0.2.16"
SRC_URI += "crate://crates.io/flate2/1.0.23"
SRC_URI += "crate://crates.io/git2-curl/0.15.0"
SRC_URI += "crate://crates.io/glob/0.3.0"
SRC_URI += "crate://crates.io/hex/0.4.3"
SRC_URI += "crate://crates.io/hex/0.3.2"
SRC_URI += "crate://crates.io/home/0.5.3"
SRC_URI += "crate://crates.io/humantime/2.1.0"
SRC_URI += "crate://crates.io/ignore/0.4.18"
SRC_URI += "crate://crates.io/im-rc/15.1.0"
SRC_URI += "crate://crates.io/jobserver/0.1.24"
SRC_URI += "crate://crates.io/lazycell/1.3.0"
SRC_URI += "crate://crates.io/lazycell/1.3.0"
SRC_URI += "crate://crates.io/libc/0.2.125"
SRC_URI += "crate://crates.io/libgit2-sys/0.13.3+1.4.2"
SRC_URI += "crate://crates.io/log/0.4.17"
SRC_URI += "crate://crates.io/memchr/2.5.0"
SRC_URI += "crate://crates.io/memchr/2.5.0"
SRC_URI += "crate://crates.io/num_cpus/1.13.1"
SRC_URI += "crate://crates.io/opener/0.5.0"
SRC_URI += "crate://crates.io/os_info/3.3.0"
SRC_URI += "crate://crates.io/os_info/3.3.0"
SRC_URI += "crate://crates.io/os_str_bytes/6.0.0"
SRC_URI += "crate://crates.io/percent-encoding/2.1.0"
SRC_URI += "crate://crates.io/pkg-config/0.3.25"
SRC_URI += "crate://crates.io/proc-macro-error/1.0.4"
SRC_URI += "crate://crates.io/proc-macro-error-attr/1.0.4"
SRC_URI += "crate://crates.io/proc-macro2/1.0.38"
SRC_URI += "crate://crates.io/quote/1.0.18"
SRC_URI += "crate://crates.io/rand_core/0.6.3"
SRC_URI += "crate://crates.io/rand_xoshiro/0.6.0"
SRC_URI += "crate://crates.io/redox_syscall/0.2.13"
SRC_URI += "crate://crates.io/regex-automata/0.1.10"
SRC_URI += "crate://crates.io/regex-syntax/0.6.25"
SRC_URI += "crate://crates.io/remove_dir_all/0.5.3"
SRC_URI += "crate://crates.io/rustc-workspace-hack/1.0.0"
SRC_URI += "crate://crates.io/rustfix/0.6.0"
SRC_URI += "crate://crates.io/ryu/1.0.9"
SRC_URI += "crate://crates.io/same-file/1.0.6"
SRC_URI += "crate://crates.io/schannel/0.1.19"
SRC_URI += "crate://crates.io/semver/1.0.9"
SRC_URI += "crate://crates.io/serde_derive/1.0.137"
SRC_URI += "crate://crates.io/serde_ignored/0.1.3"
SRC_URI += "crate://crates.io/sized-chunks/0.6.5"
SRC_URI += "crate://crates.io/socket2/0.4.4"
SRC_URI += "crate://crates.io/strip-ansi-escapes/0.1.1"
SRC_URI += "crate://crates.io/strsim/0.10.0"
SRC_URI += "crate://crates.io/strsim/0.8.0"
SRC_URI += "crate://crates.io/structopt-derive/0.4.18"
SRC_URI += "crate://crates.io/syn/1.0.92"
SRC_URI += "crate://crates.io/tar/0.4.38"
SRC_URI += "crate://crates.io/tempfile/3.3.0"
SRC_URI += "crate://crates.io/termcolor/1.1.3"
SRC_URI += "crate://crates.io/textwrap/0.11.0"
SRC_URI += "crate://crates.io/textwrap/0.15.0"
SRC_URI += "crate://crates.io/thread_local/1.1.4"
SRC_URI += "crate://crates.io/tinyvec/1.6.0"
SRC_URI += "crate://crates.io/toml_edit/0.13.4"
SRC_URI += "crate://crates.io/typenum/1.15.0"
SRC_URI += "crate://crates.io/unicode-bidi/0.3.8"
SRC_URI += "crate://crates.io/unicode-normalization/0.1.19"
SRC_URI += "crate://crates.io/unicode-segmentation/1.9.0"
SRC_URI += "crate://crates.io/unicode-width/0.1.9"
SRC_URI += "crate://crates.io/unicode-xid/0.2.3"
SRC_URI += "crate://crates.io/url/2.2.2"
SRC_URI += "crate://crates.io/utf8parse/0.2.0"
SRC_URI += "crate://crates.io/vcpkg/0.2.15"
SRC_URI += "crate://crates.io/vec_map/0.8.2"
SRC_URI += "crate://crates.io/version_check/0.9.4"
SRC_URI += "crate://crates.io/vte/0.10.1"
SRC_URI += "crate://crates.io/vte_generate_state_changes/0.1.1"
SRC_URI += "crate://crates.io/walkdir/2.3.2"
SRC_URI += "crate://crates.io/winapi/0.3.9"
SRC_URI += "crate://crates.io/winapi-i686-pc-windows-gnu/0.4.0"
SRC_URI += "crate://crates.io/winapi-util/0.1.5"
SRC_URI += "crate://crates.io/winapi-x86_64-pc-windows-gnu/0.4.0"
SRC_URI += "crate://crates.io/serde/1.0.137"
SRC_URI += "crate://crates.io/serde_json/1.0.81"
SRC_URI += "crate://crates.io/shell-escape/0.1.5"
SRC_URI += "crate://crates.io/fwdansi/1.1.0"
SRC_URI += "crate://crates.io/bitflags/1.3.2"
SRC_URI += "crate://crates.io/openssl-probe/0.1.5"
SRC_URI += "crate://crates.io/openssl-sys/0.9.73"
SRC_URI += "crate://crates.io/either/1.6.1"
SRC_URI += "crate://crates.io/aho-corasick/0.7.18"
SRC_URI += "crate://crates.io/hermit-abi/0.1.19"
SRC_URI += "crate://crates.io/crypto-hash/0.3.4"
SRC_URI += "crate://crates.io/core-foundation/0.9.3"
SRC_URI += "crate://crates.io/miow/0.3.7"
SRC_URI += "crate://crates.io/clap_lex/0.2.0"
SRC_URI += "crate://crates.io/indexmap/1.8.1"
SRC_URI += "crate://crates.io/cfg-if/1.0.0"
SRC_URI += "crate://crates.io/libz-sys/1.1.6"
SRC_URI += "crate://crates.io/cc/1.0.73"
SRC_URI += "crate://crates.io/crc32fast/1.3.2"
SRC_URI += "crate://crates.io/miniz_oxide/0.5.1"
SRC_URI += "crate://crates.io/globset/0.4.8"
SRC_URI += "crate://crates.io/bitmaps/2.1.0"
SRC_URI += "crate://crates.io/bstr/0.2.17"
SRC_URI += "crate://crates.io/itoa/1.0.1"
SRC_URI += "crate://crates.io/fastrand/1.7.0"
SRC_URI += "crate://crates.io/combine/4.6.4"
SRC_URI += "crate://crates.io/kstring/1.0.6"
SRC_URI += "crate://crates.io/form_urlencoded/1.0.1"
SRC_URI += "crate://crates.io/idna/0.2.3"
SRC_URI += "crate://crates.io/matches/0.1.9"
SRC_URI += "crate://crates.io/libssh2-sys/0.2.23"
SRC_URI += "crate://crates.io/autocfg/1.1.0"
SRC_URI += "crate://crates.io/ansi_term/0.12.1"
SRC_URI += "crate://crates.io/heck/0.3.3"
SRC_URI += "crate://crates.io/commoncrypto/0.2.0"
SRC_URI += "crate://crates.io/commoncrypto-sys/0.2.0"
SRC_URI += "crate://crates.io/openssl/0.10.40"
SRC_URI += "crate://crates.io/core-foundation-sys/0.8.3"
SRC_URI += "crate://crates.io/hashbrown/0.11.2"
SRC_URI += "crate://crates.io/libnghttp2-sys/0.1.7+1.45.0"
SRC_URI += "crate://crates.io/adler/1.0.2"
SRC_URI += "crate://crates.io/fnv/1.0.7"
SRC_URI += "crate://crates.io/once_cell/1.10.0"
SRC_URI += "crate://crates.io/arrayvec/0.5.2"
SRC_URI += "crate://crates.io/instant/0.1.12"
SRC_URI += "crate://crates.io/bytes/1.1.0"
SRC_URI += "crate://crates.io/foreign-types/0.3.2"
SRC_URI += "crate://crates.io/foreign-types-shared/0.1.1"
SRC_URI += "crate://crates.io/openssl-macros/0.1.0"
SRC_URI += "crate://crates.io/tinyvec_macros/0.1.0"




# do_install () {
#     # install the symlink to /sbin/init
#     # we've chosen for compatibility with update-rc.d, implement this in your background services

#     mkdir -m 755 ${D}/sbin
#     ln -sfr ${D}/${bindir}/${COMPONENT} ${D}/sbin/
# }


BBCLASSEXTEND = "native nativesdk"
# require recipes-devtools/rust/rust-source-${PV}.inc
# require recipes-devtools/rust/rust-snapshot-${PV}.inc
# require cargo.inc

