@version: 4.6

source s_sys {
    internal();
    systemd_journal();
};

destination d_socket {
    unix-dgram("/run/log.sock");
};

log {
    source(s_sys);
    destination(d_socket);
};

options {
    stats(freq(0));
};
